### ISSUE TITLE
Check if pip is already installed and if so, don't install it.

### ISSUE THREAD

**Issue by WowSuchRicky** [tylermuch/dotfiles#1]
I can't PR this since I already have a fork that I am using, but just replace:

` sudo easy-install pip`

with:

```bash
if hash pip 2>/dev/null; then
    echo "pip already installed, exiting..."
    exit
fi

sudo easy_install pip
```

Per: http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script

**Comment by tylermuch** [comment]
done

**Comment by WowSuchRicky** [comment]
cool and good

**Comment by tylermuch** [comment]
thank
